name: test_consumer
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # test_package:
  #   git:
  #     url: https://github.com/marshall-buck/test_package.git
  usda_db_package:
    git:
      url: https://github.com/marshall-buck/usda_db_package.git




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true


